services:
  memcached:
    image: memcached:1.6
  nginx:
    depends_on:
      - php
    image: nginx:1.18
    volumes:
      - ./services/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - nginx-ssl:/etc/ssl/site:ro
      - php-src:/var/www/php_src:ro
  php:
    build:
      context: ./services/php/build
    depends_on:
      - memcached
      - redis
    volumes:
      - ./services/php/composer/setup.sh:/opt/bin/composer-setup.sh:ro
      - php-src:/var/www/php_src
    working_dir: /var/www/php_src
  redis:
    command: redis-server /etc/redis/conf.d/redis.conf
    image: redis:latest
    volumes:
      - ./services/redis/conf.d:/etc/redis/conf.d

volumes:
    nginx-ssl:
    php-src:
